[paths]
; Auto installer overwrites this. Prefer the install that has CLEO.asi
gta_dir = E:\GTA San Andreas

gallery_dir = C:\Users\Josh\Documents\GTA San Andreas User Files\Gallery
gallery_dir_alt = C:\Users\Josh\My Documents\GTA San Andreas User Files\Gallery

[server]
host = 0.0.0.0
port = 8088
open_browser = 1
max_photos = 40
